### ISSUE TITLE
Fix the screens that wont scale

### ISSUE THREAD

**Issue by ElPumpo** [Council-of-the-Delverers/Delver-Unlimited#2]
![low_res](https://user-images.githubusercontent.com/12564301/29267477-2c0262f8-80e9-11e7-8a98-bcb3947366ad.png)

`--width=1024 --height=600`

**Comment by HawaiiBeach** [comment]
https://github.com/libgdx/libgdx/wiki/Table

**Comment by HawaiiBeach** [comment]
![namnlos](https://user-images.githubusercontent.com/12564301/29531323-59d26c4a-86a8-11e7-9a4e-010199b5286e.png)
